# Introduction

```{r}
#| echo: false

source("_common.R")
```

Welcome to the **cd2030 User Guide**! This guide is designed to help you navigate the features and functionality of the cd2030 Shiny app. It provides step-by-step instructions for data loading, analysis, visualization, and report generation.

## About the App

The cd2030 Shiny App is a tool for analysing, visualizing, and reporting cd2030 vaccines data. Designed for researchers, policy makers, and program managers, it integrates various datasets including **UN estimates**, **WUENIC estimates**, **survey data**, and **health facility data**, to generate actionable insights and customizable reports.

## Key Features

The app offers a range features to streamline your data analysis workflow:

-   **Data Integration**: Easily upload and manage data from multiple sources. Supported formats and specific instructions will be detailed in the "Data Input" section.
-   **Dynamic Visualizations**: Generate charts, tables, and summaries to explore trends and patterns.
-   **Custom Annotations**: Add notes and explanations directly within the app to enhance documentation and provide context for your analysis.
-   **Report Generation**: Create reports in various formats to suit your needs.

## Prerequisites

Before using the app, ensure you have the following:

-   **Software**
    -   **R (version 4.0 or higher)**
    -   **RStudio**
-   **R Packages**: The required R packages will be automatically installed upon first launch if not already present. A full list of dependencies can be found in the "Installation" section.
-   **Data**: Access to necessary datasets
    -   **UN estimates**
    -   **WUENIC estimates**
    -   Country-specific **survey data**
    -   **Health facility datasets** for analysis.

## How to Use This Guide

This guide is structured to guide you through the app's functionalities, from set-up to advanced usage. Use the sidebar to navigate to specific sections:

-   **Installation:** Detailed instructions for installing the app and its dependencies.
-   **Data Input:** Step-by-step guidance on loading and managing your data.
-   **Data Analysis and Visualization:** Comprehensive explanations of the available analytical tools and visualization options.
-   **Report Generation:** Instructions on creating reports.
-   **Troubleshooting:** Solutions to common issues and frequently asked questions.

## Acknowledgement

This app and guide were developed by the **African Population and Health Research Centre (APHRC)**.
